CN – Fortran Program
CN Program
francisco rivera alvarez
76 statements
Source File
Programa para el calculo de flechas de una placa apoyada en sus cantos con carga hidraulica hasta la mitad de su largo
Calls
Variables
matriz f n m fMatriz forma orden asserts
Interfaces
constructor
Subroutines
header printMatrix printVector
Variables
Type Attributes Name Initial
real(kind=8), dimension(:,:), allocatable :: matriz
sistema de ecuaciones
real(kind=8), dimension(:), allocatable :: f
vector terminos independientes
integer :: n
numero de puntos para discretizar largo(n) y ancho(m)
integer :: m
numero de puntos para discretizar largo(n) y ancho(m)
real(kind=8), dimension(:,:), allocatable :: fMatriz
solucion en forma matricial
integer, dimension(2) :: forma
forma de la matriz solucion
integer, dimension(2) :: orden = (/2, 1/)
orden de los numeros al cambiar vector a matriz solucion
logical :: asserts = .FALSE.
si se activa se imprimen los datos de la factorizacion
Interfaces
interface
Interface para poder fijar las dimensiones de la matriz en la subroutine constructor
subroutine constructor(matriz, f, n, m)
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(inout), dimension(:,:), allocatable :: matriz
sistema de ecuaciones
real(kind=8), intent(inout), dimension(:), allocatable :: f
vector terminos independientes
integer, intent(out) :: n
integer, intent(out) :: m
Subroutines
subroutine header(label)
Imprime una linea, un texto centrado y una línea. Creando como un titulo.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: label
subroutine printMatrix(matriz, label)
Imprime una matriz mas un texto como titulo.
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:,:) :: matriz
character(len=*), intent(in) :: label
subroutine printVector(f, label)
Imprime un vector mas un texto como titulo
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: f
character(len=*), intent(in) :: label
All Programs
CN
Call graph
cn calls constructor, bienvenido, linearsystem, commandline, printmatrix, printvector, fcholesky
printmatrix calls header, linea
printvector calls header, linea
header calls linea