WALLTER – Fortran Program
WALLTER Program
francisco rivera alvarez
82 statements
Source File
Programa para el calculo de flechas de una placa apoyada en sus cantos con carga hidraulica hasta la mitad de su largo
Calls
Common Blocks
unnamed
Variables
matriz f navier fMatriz forma orden resultsFile configFile asserts exists ancho largo espesor rigidez n m
Subroutines
header printMatrix printVector
Common Blocks
common
variables globales
Type Attributes Name Initial
real :: resultsFile
real :: configFile
Variables
Type Attributes Name Initial
real(kind=8), dimension(:,:), allocatable :: matriz
sistema de ecuaciones
real(kind=8), dimension(:), allocatable :: f
vector terminos independientes
real(kind=8), dimension(:,:), allocatable :: navier
vector terminos analiticos
real(kind=8), dimension(:,:), allocatable :: fMatriz
solucion en forma matricial
integer, dimension(2) :: forma
forma de la matriz solucion
integer, dimension(2) :: orden = (/2, 1/)
orden de los numeros al cambiar vector a matriz solucion
character(len=50) :: resultsFile = './result/resultados.html'
directorio donde se escribiran los resultados
character(len=50) :: configFile = ''
directorio donde se encuentran los config file
logical :: asserts = .FALSE.
si se activa se imprimen los datos de la factorizacion
logical :: exists
comprueba la existencia de los directorios de resultados
real(kind=8) :: ancho
dimensiones de la placa
real(kind=8) :: largo
dimensiones de la placa
real(kind=8) :: espesor
dimensiones de la placa
real(kind=8) :: rigidez
rigidez a flexion de la placa
integer :: n
numero de puntos para discretizar largo(n) y ancho(m)
integer :: m
numero de puntos para discretizar largo(n) y ancho(m)
Subroutines
subroutine header(label)
Imprime una linea, un texto centrado y una línea. Creando como un titulo.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: label
subroutine printMatrix(matriz, label)
Imprime una matriz mas un texto como titulo.
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:,:) :: matriz
character(len=*), intent(in) :: label
subroutine printVector(f, label)
Imprime un vector mas un texto como titulo
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:) :: f
character(len=*), intent(in) :: label
All Programs
WALLTER
Call graph
wallter calls printvector, analiticanavier, linearsystem, bienvenido, commandline, fcholesky, datos, constructvector, constructmatriz, resnumericos, printmatrix, resanaliticos
printvector calls header, linea
analiticanavier calls linea
datos calls linea, exportplaca, exportmaterial, createhtml
printmatrix calls header, linea
header calls linea