header – Fortran Program
header Subroutine
12 statements
Source File
subroutine header(label)
Imprime una linea, un texto centrado y una lï¿½nea. Creando como un titulo.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: label
Calls
Called By
All Procedures
analiticaNavier bienvenido commandLine constructMatriz constructVector createHTML datos exportMaterial exportPlaca fCholesky header linea linearSystem printMatrix printVector resAnaliticos resNumericos vectorToMatrix
Call graph
header calls linea
printmatrix calls header
printvector calls header
wallter calls printmatrix, printvector