linea – Fortran Program
linea Subroutine
3 statements
Source File
subroutine linea()
Imprime una lï¿½nea de 60 caracteres. Se usa para separar la informacion que se imprime en la pantalla
Arguments
None
Called By
All Procedures
analiticaNavier bienvenido commandLine constructMatriz constructVector createHTML datos exportMaterial exportPlaca fCholesky header linea linearSystem printMatrix printVector resAnaliticos resNumericos vectorToMatrix
Call graph
printmatrix calls linea, header
datos calls linea
analiticanavier calls linea
header calls linea
printvector calls linea, header
wallter calls printmatrix, datos, analiticanavier, printvector