printMatrix – Fortran Program
printMatrix Subroutine
10 statements
Source File
subroutine printMatrix(matriz, label)
Imprime una matriz mas un texto como titulo.
Arguments
Type Intent Optional Attributes Name
real(kind=8), intent(in), dimension(:,:) :: matriz
character(len=*), intent(in) :: label
Calls
Called By
All Procedures
analiticaNavier bienvenido commandLine constructMatriz constructVector createHTML datos exportMaterial exportPlaca fCholesky header linea linearSystem printMatrix printVector resAnaliticos resNumericos vectorToMatrix
Call graph
printmatrix calls header, linea
header calls linea
wallter calls printmatrix